name = "readfile-bench"
version = "0.1.0"
license = "MIT"
author = "fpm maintainers"
maintainer = "zuo.zhihua@qq.com"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
timer = { git = "https://github.com/zoziha/timer.git" }
openmp = "*"
